services:
  - type: web
    env: docker
    name: ples-prod-server1
    repo: https://gitlab.com/programtvogkompjutera1/ples
    branch: master
    buildFilter:
      path: 
        - server/**
    envVars:
      - key: POSTGRES_HOST
        fromDatabase: ples-prod-db1
        property: host
      - key: POSTGRES_DB
        fromDatabase: ples-prod-db1
        property: database
      - key: POSTGRES_USER
        fromDatabase: ples-prod-db1
        property: user
      - key: POSTGRES_PASSWORD
        fromDatabase: ples-prod-db1
        property: password
      - key: PORT
        value: 3001

  - type: web
    env: docker
    name: ples-prod-client1
    repo: https://gitlab.com/programtvogkompjutera1/ples
    branch: master
     buildFilter:
      path: 
        - client/**
    envVars:
      - key: PORT
        value: 3000

databases:
  - name: ples-prod-db1
