version: '3'

services:
  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: ples
      POSTGRES_USER: ples
      POSTGRES_PASSWORD: ples
    ports:
      - 3002:5432

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: on-failure
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ples
      POSTGRES_USER: ples
      POSTGRES_PASSWORD: ples
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET?err}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION?err}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET?err}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION?err}
      SALT_ROUNDS: ${SALT_ROUNDS?err}
      PORT: 3001
    ports:
      - 3001:3001
    depends_on:
      - db

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server
